### ISSUE TITLE
Phantom Storm module issue

### ISSUE THREAD

**Issue by benedhk** [smythtech/sdnpwn#6]
Hi dylan, 

I just tried to run phantom storm module and it shows an error

```
root@Linux:~/sdnpwn# ./sdnpwn.py phantom-storm --iface h1-eth0 --target 10.0.0.0/24 --phantom-ip 10.1.1.1 --packets 1000
[+] Building list of target hosts (may take a minute)
[+] Found 8 targets in total
[+] Generated Phantom host MAC: 63:65:65:91:f1:42
[+] Starting attack
[+] Sending gratuitous ARP for legitimate host to 10.0.0.3
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/root/sdnpwn/modules/dp_arp_poison.py", line 35, in arpCachePoison
    sendp(Ether(src=thisHostMAC, dst=vicMAC)/ARP(hwsrc=thisHostMAC, pdst=thisHostIP))
  File "/usr/local/lib/python3.5/dist-packages/scapy-2.4.3rc1.dev154-py3.5.egg/scapy/sendrecv.py", line 345, in sendp
    realtime=realtime, return_packets=return_packets)
  File "/usr/local/lib/python3.5/dist-packages/scapy-2.4.3rc1.dev154-py3.5.egg/scapy/sendrecv.py", line 298, in __gen_send
    s.send(p)
  File "/usr/local/lib/python3.5/dist-packages/scapy-2.4.3rc1.dev154-py3.5.egg/scapy/arch/linux.py", line 494, in send
    return SuperSocket.send(self, x)
  File "/usr/local/lib/python3.5/dist-packages/scapy-2.4.3rc1.dev154-py3.5.egg/scapy/supersocket.py", line 47, in send
    sx = raw(x)
  File "/usr/local/lib/python3.5/dist-packages/scapy-2.4.3rc1.dev154-py3.5.egg/scapy/compat.py", line 51, in raw
    return bytes(x)
  File "/usr/local/lib/python3.5/dist-packages/scapy-2.4.3rc1.dev154-py3.5.egg/scapy/packet.py", line 442, in __bytes__
    return self.build()
  File "/usr/local/lib/python3.5/dist-packages/scapy-2.4.3rc1.dev154-py3.5.egg/scapy/packet.py", line 557, in build
    p = self.do_build()
  File "/usr/local/lib/python3.5/dist-packages/scapy-2.4.3rc1.dev154-py3.5.egg/scapy/packet.py", line 539, in do_build
    pkt = self.self_build()
  File "/usr/local/lib/python3.5/dist-packages/scapy-2.4.3rc1.dev154-py3.5.egg/scapy/packet.py", line 520, in self_build
    p = f.addfield(self, p, val)
  File "/usr/local/lib/python3.5/dist-packages/scapy-2.4.3rc1.dev154-py3.5.egg/scapy/fields.py", line 139, in addfield
    return s + struct.pack(self.fmt, self.i2m(pkt, val))
  File "/usr/local/lib/python3.5/dist-packages/scapy-2.4.3rc1.dev154-py3.5.egg/scapy/layers/l2.py", line 123, in i2m
    return MACField.i2m(self, pkt, self.i2h(pkt, x))
  File "/usr/local/lib/python3.5/dist-packages/scapy-2.4.3rc1.dev154-py3.5.egg/scapy/fields.py", line 487, in i2m
    return mac2str(x)
  File "/usr/local/lib/python3.5/dist-packages/scapy-2.4.3rc1.dev154-py3.5.egg/scapy/utils.py", line 403, in mac2str
    return b"".join(chb(int(x, 16)) for x in plain_str(mac).split(':'))
  File "/usr/local/lib/python3.5/dist-packages/scapy-2.4.3rc1.dev154-py3.5.egg/scapy/utils.py", line 403, in <genexpr>
    return b"".join(chb(int(x, 16)) for x in plain_str(mac).split(':'))
ValueError: invalid literal for int() with base 16: ''
```
Do you have any idea why this might happening?

Thanks,
Ben

**Comment by smythtech** [comment]
It looks like one of the MAC addresses going into the frame is blank. I'll check it out and get back to you.

**Comment by smythtech** [comment]
Ok, I've ironed out a few issues in the module. Also, make sure the phantom IP is in the same network as the targets.Try executing it like so:
./sdnpwn.py phantom-storm --iface h1-eth0 --target 10.0.0.0/24 --phantom-ip 10.0.0.200 --packets 1000

**Comment by benedhk** [comment]
Thanks for your response!

but unfortunately, it still produces the exact same error..

**Comment by smythtech** [comment]
Can you give me some details of the network you're using so I can replicate it? Which controller, how many hosts, switches, links, etc.

There seems to be some issue getting the MAC address or either the local interface or the target hosts

**Comment by benedhk** [comment]
for the controller, i use onos 1.6.0
hosts = 9
switch = 3
